"""initial origin schema — 7 tables

Revision ID: 0001_initial_origin
Revises:

Hand-written (not autogenerated) so the schema is deterministic and reviewable.
Creates: persons, platform_settings, passkey_credentials, otp_codes,
api_keys, server_credentials, grants. Cross-dialect SQLAlchemy types only —
the engine is SQLite. Case-insensitive columns (email, username, otp email)
use `COLLATE NOCASE` to preserve the CITEXT semantics this schema replaced.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial_origin"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---- persons ---------------------------------------------------------
    op.create_table(
        "persons",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("email", sa.String(length=256, collation="NOCASE"), nullable=True),
        sa.Column("username", sa.String(length=256, collation="NOCASE"), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False, server_default=""),
        sa.Column("picture", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("oidc_provider", sa.String(length=64), nullable=True),
        sa.Column("oidc_subject", sa.String(length=256), nullable=True),
        sa.Column("google_id", sa.String(length=256), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("email", name="uq_persons_email"),
        sa.UniqueConstraint("username", name="uq_persons_username"),
    )
    op.create_index(
        "ix_persons_oidc_identity",
        "persons",
        ["oidc_provider", "oidc_subject"],
        unique=True,
        sqlite_where=sa.text("oidc_provider IS NOT NULL"),
    )
    op.create_index("ix_persons_google_id", "persons", ["google_id"])

    # ---- platform_settings -----------------------------------------------
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(length=128), primary_key=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("secret_value", sa.Text(), nullable=True),
        sa.Column("is_secret", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column(
            "updated_by",
            sa.Uuid(),
            sa.ForeignKey("persons.id", name="fk_platform_settings_updated_by_persons"),
            nullable=True,
        ),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_platform_settings_category", "platform_settings", ["category"])

    # ---- passkey_credentials ---------------------------------------------
    op.create_table(
        "passkey_credentials",
        sa.Column("id", sa.String(length=512), primary_key=True),
        sa.Column(
            "person_id",
            sa.Uuid(),
            sa.ForeignKey(
                "persons.id", ondelete="CASCADE", name="fk_passkey_credentials_person_id_persons"
            ),
            nullable=False,
        ),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("transports", sa.JSON(), nullable=True),
        sa.Column("aaguid", sa.String(length=64), nullable=True),
        sa.Column("device_name", sa.String(length=128), nullable=True),
        sa.Column("backup_eligible", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("backup_state", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_passkey_credentials_person_id", "passkey_credentials", ["person_id"])

    # ---- otp_codes -------------------------------------------------------
    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("email", sa.String(length=256, collation="NOCASE"), nullable=False),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("used", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_otp_codes_email", "otp_codes", ["email"])
    op.create_index("ix_otp_codes_expires_at", "otp_codes", ["expires_at"])
    op.create_index("ix_otp_codes_used", "otp_codes", ["used"])
    op.create_index(
        "ix_otp_codes_email_used_expires", "otp_codes", ["email", "used", "expires_at"]
    )

    # ---- api_keys --------------------------------------------------------
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("persons.id", ondelete="CASCADE", name="fk_api_keys_user_id_persons"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("display_label", sa.String(length=256), nullable=True),
        sa.Column("client_id", sa.String(length=256), nullable=True),
        sa.Column("host_id", sa.Uuid(), nullable=True),
        sa.Column("server_id", sa.Uuid(), nullable=True),
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("issued_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_from_client_id", sa.String(length=256), nullable=True),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("requires_nonce", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("scopes", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("resource_filters", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("key_hash", name="uq_api_keys_key_hash"),
    )
    op.create_index("ix_api_keys_user_id", "api_keys", ["user_id"])
    op.create_index("ix_api_keys_client_id", "api_keys", ["client_id"])
    op.create_index("ix_api_keys_key_hash", "api_keys", ["key_hash"])

    # ---- server_credentials ----------------------------------------------
    op.create_table(
        "server_credentials",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("client_id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("secret_hash", sa.Text(), nullable=False),
        sa.Column("authority", sa.String(length=256), nullable=False),
        sa.Column("host_id", sa.Uuid(), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=False),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("persons.id", name="fk_server_credentials_user_id_persons"),
            nullable=False,
        ),
        sa.Column("scopes", sa.JSON(), nullable=False, server_default=sa.text("'[]'")),
        sa.Column("resource_filters", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("client_id", name="uq_server_credentials_client_id"),
    )
    op.create_index("ix_server_credentials_client_id", "server_credentials", ["client_id"])

    # ---- grants ----------------------------------------------------------
    op.create_table(
        "grants",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("grantee_type", sa.String(length=16), nullable=False),
        sa.Column("grantee_id", sa.String(length=256), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=False),
        sa.Column("effect", sa.String(length=8), nullable=False, server_default=sa.text("'allow'")),
        sa.Column("can_create", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_read", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("can_update", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_delete", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_evict", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_invoke", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_add", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_share", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("can_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("requires_identity", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("read_requires_identity", sa.Boolean(), nullable=True),
        sa.Column("write_requires_identity", sa.Boolean(), nullable=True),
        sa.Column("invoke_requires_identity", sa.Boolean(), nullable=True),
        sa.Column("target_entity", sa.String(length=256), nullable=True),
        sa.Column("target_entity_type", sa.String(length=32), nullable=True),
        sa.Column("max_claims", sa.Integer(), nullable=True),
        sa.Column("claims_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("state", sa.String(length=16), nullable=False, server_default=sa.text("'active'")),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Uuid(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_time", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_grants_resource_id", "grants", ["resource_id"])
    op.create_index("ix_grants_state", "grants", ["state"])
    op.create_index("ix_grants_expires_at", "grants", ["expires_at"])
    op.create_index(
        "ix_grants_grantee_resource_state", "grants", ["grantee_id", "resource_id", "state"]
    )
    op.create_index(
        "ix_grants_grantee_type_id_state", "grants", ["grantee_type", "grantee_id", "state"]
    )
    op.create_index(
        "ix_grants_resource_active",
        "grants",
        ["resource_id", "state"],
        sqlite_where=sa.text("state = 'active'"),
    )


def downgrade() -> None:
    op.drop_table("grants")
    op.drop_table("server_credentials")
    op.drop_table("api_keys")
    op.drop_table("otp_codes")
    op.drop_table("passkey_credentials")
    op.drop_table("platform_settings")
    op.drop_table("persons")
